services:
  mysql:
    image: mysql:8
    container_name: player_one_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - player_one_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d

volumes:
  player_one_data: